# DL4G - Jass Introduction

In this exercise we will look at some properties of the jass kit environment that can be used to develop your own jass agent.

You will need to have numpy installed, as well as the jass-kit environment.

In [2]:
import numpy as np
import random

from jass.game.game_util import *
from jass.game.game_state_util import *
from jass.game.game_sim import GameSim
from jass.game.game_observation import GameObservation
from jass.game.const import *
from jass.game.rule_schieber import RuleSchieber
from jass.agents.agent import Agent
from jass.agents.agent_random_schieber import AgentRandomSchieber
from jass.arena.arena import Arena

from simple_agent import *


Another possibility to test agents locally is to use the arena. Let us play 100 games against the Random Agent and see if our trump methods makes any difference.


In [3]:
arena = Arena(nr_games_to_play=100)
arena.set_players(MyAgent(), AgentRandomSchieber(), MyAgent(), AgentRandomSchieber())

In [4]:
arena.play_all_games()

hand: [ 0  2  8 31]
choice: 31
hand: [ 3  4  6 11 17 20 21 22 25]
choice: 3
hand: [ 4  6 11 17 20 21 22 25]
choice: 20
hand: [ 0  2  8 19]
choice: 0
hand: [ 2  8 12 14 15 16 19]
choice: 16
hand: [ 4  6 11 17]
choice: 17
hand: [ 2  8 12 14 15 19]
choice: 8
hand: [ 4  6 11 21 22 25]
choice: 11
hand: [ 4  6 21 22 25]
choice: 6
hand: [ 2 19]
choice: 2
hand: [12 14 15 19]
choice: 15
hand: [ 4 21 22 25]
choice: 4
hand: [21 22 25]
choice: 25
hand: [19]
choice: 19
hand: [12 14]
choice: 12
hand: [21 22]
choice: 21
hand: [22]
choice: 22
hand: [14]
choice: 14
hand: [ 0  5 10 11 19 21 22 30 32]
choice: 21
hand: [24 26]
choice: 26
hand: [ 2  4  6  7 33]
choice: 4
hand: [ 0  5 30 32]
choice: 32
hand: [ 0  5 10 11 19 22 30]
choice: 10
hand: [12 16 33]
choice: 16
hand: [ 0  5 11 19 22 30]
choice: 22
hand: [24]
choice: 24
hand: [ 0  5 11 19 30]
choice: 0
hand: [33]
choice: 33
hand: [ 2  6  7 12]
choice: 12
hand: [11 30]
choice: 11
hand: [19 30]
choice: 19
hand: [2 6 7]
choice: 2
hand: [ 5 30]
choice: 5

In [5]:
print(arena.points_team_0.sum(), arena.points_team_1.sum())

8858.0 6842.0


Now you can continue with a rule based implemenation of the card play. Also look at the flask implementation of the service to see how you can get your agent online.

In [ ]:
from mcts_agent import MCTSAgent

rule = RuleSchieber()
game = GameSim(rule=rule)
agent = MCTSAgent()

np.random.seed(1)
game.init_from_cards(hands=deal_random_hand(), dealer=NORTH)
obs = game.get_observation()
trump = agent.action_trump(obs)
game.action_trump(trump)

while not game.is_done():
    game.action_play_card(agent.action_play_card(game.get_observation()))

print(game.state.points)


random cards for game simulation
[[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 1 0 0 1 0 1 1 0 0]
 [0 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 0 1 0 1 0 0 0 0 0 1 0]
 [1 1 0 0 0 1 0 0 1 1 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
random cards for game simulation
[[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 0 0 0 1 0 0 1 1 0 1]
 [0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 0 0 0 1 0]
 [1 1 0 0 0 1 0 0 1 1 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
random cards for game simulation
[[0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 1 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 1 0 1 1]
 [0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 1 0 0 1 0 0]
 [1 1 0 0 0 1 0 0 1 1 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [38]:
from jass.arena.arena import Arena

# Assume MCTSAgent and MyAgent are already defined and implemented

# Define the number of games to simulate
num_games = 100

# Initialize the Arena
arena = Arena(nr_games_to_play=num_games)

# Set up the players: Teams 0 and 1 each have 2 players
# Here, team 0 consists of MCTSAgent, and team 1 consists of MyAgent
arena.set_players(MCTSAgent(), AgentRandomSchieber(), MCTSAgent(), AgentRandomSchieber())

# Play all the games
arena.play_all_games()

# Retrieve and display the points scored by each team across all games
team_0_points = arena.points_team_0.sum()
team_1_points = arena.points_team_1.sum()

print(f"Team 0 (MCTSAgent) Total Points: {team_0_points}")
print(f"Team 1 (MyAgent) Total Points: {team_1_points}")

# Optionally, you can calculate win ratios
team_0_wins = (arena.points_team_0 > arena.points_team_1).sum()
team_1_wins = (arena.points_team_1 > arena.points_team_0).sum()

print(f"Team 0 (MCTSAgent) Wins: {team_0_wins}")
print(f"Team 1 (MyAgent) Wins: {team_1_wins}")


[........................................]  100/ 100 games played
Team 0 (MCTSAgent) Total Points: 9697.0
Team 1 (MyAgent) Total Points: 6003.0
Team 0 (MCTSAgent) Wins: 75
Team 1 (MyAgent) Wins: 25
